select = [
	"E", "F", "W",	# flake8
	"ARG",	# flake8-unused-arguments
	"B", "B904",	# flake8-bugbear
	"C4",	# flake8-comprehensions
	"D",	# pydocstyle
	"D211", # no-blank-line-before-class
	"D213", # multi-line-summary-second-line
	"EM",	# flake8-errmsg
	"EXE",	# flake8-executable
	"G",	# flake8-logging-format
	"I",	# isort
	"ICN",	# flake8-import-conventions
	"ISC",	# flake8-implicit-str-concat
	"NPY",	# NumPy specific rules
	"PD",	# pandas-vet
	"PGH",	# pygrep-hooks
	"PIE",	# flake8-pie
	"PL",	# pylint
	"PT",	# flake8-pytest-style
	"PTH",	# flake8-use-pathlib
	# "RET",	# flake8-return
	"RUF",	# Ruff-specific
	"SIM",	# flake8-simplify
	# "T20",	# flake8-print
	"UP",	# pyupgrade
	"YTT",	# flake8-2020
]
extend-ignore = [
	"D100",	# Missing docstring in public module
	"D101",	# Missing docstring in public class
	"D102",	# Missing docstring in public method
	"D103",	# Missing docstring in public function
	"D203",	# One blank line before class
	"D206",	# Docstring should be indented with spaces, not tabs
	"D213",	# multi-line-summary-first-line
	# "E501",	# Line too long
	# "PLR",	# Design related pylint codes
	# "PT004",	# Use underscore for non-returning fixture (use usefixture instead)
	"RET504",	# Unnecessary variable assignment before return statement
]
target-version = "py39"
typing-modules = ["serpent.typing"]
src = ["src"]
unfixable = [
	"T20",	# Removes print statements
	"F841",	# Removes unused variables
]
exclude = []
flake8-unused-arguments.ignore-variadic-names = true
isort.required-imports = ["from __future__ import annotations"]

[per-file-ignores]
"tests/**" = ["T20"]
